//! Compiles ctok's finite vocabulary into an exact minimum-cost counting DFA.
//! Each active trie prefix carries the best cost before it started, relative to
//! the current complete segmentation. Extending a prefix either keeps it active
//! or completes a one-token piece. Subtracting the new minimum yields a canonical
//! residual state; the subtracted amount is the transition's signed cost delta.
//! The byte fallback is an implicit one-token edge for every byte. UTF-8 prefix
//! pieces and single-scalar pieces reproduce the runtime character floor on valid
//! UTF-8, including the internal ASCII markers.

use rustc_hash::FxHashMap;
use std::collections::{BTreeMap, BTreeSet};

#[derive(Default)]
struct Node {
    edges: BTreeMap<u8, u32>,
    terminal: bool,
}

// Reuse the defining rules without including any of the generated binary tables.
#[allow(dead_code, reason = "generator only needs variable-length decoding")]
#[path = "../../../src/claude/compression.rs"]
mod compression;
#[allow(dead_code, reason = "shared module also contains runtime-only helpers")]
#[path = "../../../src/claude/constants.rs"]
mod constants;
#[allow(dead_code, reason = "shared module also contains runtime-only helpers")]
#[path = "../../../src/claude/properties.rs"]
mod properties;

fn main() -> anyhow::Result<()> {
    use anyhow::{Context, bail};
    let mut check = false;
    let mut output = None;
    for arg in std::env::args_os().skip(1) {
        if arg == "--check" {
            check = true;
        } else if arg == "--help" || arg == "-h" {
            println!(
                "Usage: gen-tables [--check] [OUTPUT_DIRECTORY]\nGenerate all five tables from the bundled vocabulary and shared Unicode rules.\n--check compares generated bytes with existing files without changing them."
            );
            return Ok(());
        } else if arg.to_string_lossy().starts_with('-') || output.is_some() {
            bail!("usage: gen-tables [--check] [OUTPUT_DIRECTORY]");
        } else {
            output = Some(std::path::PathBuf::from(arg));
        }
    }
    let output = output.unwrap_or_else(|| {
        std::path::Path::new(env!("CARGO_MANIFEST_DIR")).join("../../src/claude/data")
    });
    let pieces = read_pieces();
    validate_fast_paths(&pieces);
    let (floor, multi_scalar) = scalar_tables(&pieces);
    let trie = build_trie(&pieces);
    let rows = minimize(&determinize(&trie));
    validate_dfa(&trie, &rows, &pieces);
    let mut character = Vec::with_capacity(65536 * 2);
    for cp in 0..65536 {
        character.extend(
            char::from_u32(cp)
                .map_or(0, |ch| properties::Character::compute(ch).0)
                .to_le_bytes(),
        );
    }
    let tables = [
        ("count_dfa_v4_7.bin", serialize(&rows)),
        ("multi_scalar.bin", multi_scalar),
        ("floor_v4_7.bin", floor),
        ("character.bin", character),
        ("ascii_words.bin", short_words(&trie)),
    ];
    if !check {
        std::fs::create_dir_all(&output)?;
    }
    for (name, bytes) in tables {
        let compressed =
            zstd::bulk::compress(&bytes, 19).with_context(|| format!("cannot compress {name}"))?;
        // Verify the exact frame with the runtime decoder before publishing it.
        assert_eq!(compression::decode(&compressed), bytes, "{name} round trip");
        let name = format!("{name}.zst");
        let path = output.join(&name);
        if check {
            let current =
                std::fs::read(&path).with_context(|| format!("cannot read {}", path.display()))?;
            if current != compressed {
                bail!("{name} differs; regenerate the tables");
            }
            eprintln!("{name}: matches");
        } else {
            std::fs::write(&path, &compressed)
                .with_context(|| format!("cannot write {}", path.display()))?;
            eprintln!("{name}: {} -> {} bytes", bytes.len(), compressed.len());
        }
    }
    Ok(())
}

fn read_pieces() -> BTreeSet<Vec<u8>> {
    let input: serde_json::Value =
        serde_json::from_str(include_str!("../data/pieces_v4_7.json")).unwrap();
    let mut pieces = BTreeSet::new();
    for (section, entries) in input["tokens"].as_object().unwrap() {
        for entry in entries.as_array().unwrap() {
            let key = entry.as_str().unwrap();
            if section == "bytes_fallback" {
                pieces.insert(
                    (0..key.len())
                        .step_by(2)
                        .map(|i| u8::from_str_radix(&key[i..i + 2], 16).unwrap())
                        .collect::<Vec<_>>(),
                );
            } else {
                let key = key
                    .replace("⟨bow⟩", "\x01")
                    .replace("⟨eow⟩", "\x02")
                    .replace("⟨shift⟩", "\x03")
                    .replace("⟨caps⟩", "\x04");
                if section == "contractions" {
                    pieces.insert(format!("{key}\x02").into_bytes());
                }
                pieces.insert(key.into_bytes());
            }
        }
    }
    pieces
}

fn build_trie(pieces: &BTreeSet<Vec<u8>>) -> Vec<Node> {
    let mut trie = vec![Node::default()];
    for piece in pieces {
        // The runtime's independent word cache depends on these exact seams.
        for (index, &byte) in piece.iter().enumerate() {
            match byte {
                1 => assert!(index == 0 || index == 1 && piece[0] == 3),
                2 => assert_eq!(index + 1, piece.len()),
                3 => assert_eq!(index, 0),
                _ => {}
            }
        }
        let mut node = 0;
        for &b in piece {
            let child = if let Some(&child) = trie[node].edges.get(&b) {
                child
            } else {
                let child = u32::try_from(trie.len()).expect("too many trie nodes");
                trie.push(Node::default());
                trie[node].edges.insert(b, child);
                child
            };
            node = child as usize;
        }
        trie[node].terminal = true;
    }
    trie
}

fn determinize(trie: &[Node]) -> Vec<u32> {
    let mut states = vec![Vec::<(u32, i8)>::new()];
    let mut ids = FxHashMap::default();
    ids.insert(states[0].clone(), 0u32);
    let mut rows = Vec::<u32>::new();
    let mut index = 0;
    while index < states.len() {
        let state = states[index].clone();
        let mut nexts: [Vec<(u32, i8)>; 256] = std::array::from_fn(|_| Vec::new());
        for (node, cost) in std::iter::once((0, 0)).chain(state) {
            for (&b, &child) in &trie[node as usize].edges {
                nexts[b as usize].push((child, cost));
            }
        }
        for mut next in nexts {
            let cost = next
                .iter()
                .filter(|(n, _)| trie[*n as usize].terminal)
                .map(|(_, c)| c.checked_add(1).expect("residual cost overflow"))
                .min()
                .unwrap_or(1)
                .min(1);
            next.retain(|(n, _)| !trie[*n as usize].edges.is_empty());
            for (_, c) in &mut next {
                *c = c.checked_sub(cost).expect("residual cost overflow");
            }
            next.sort_unstable();
            let id = if let Some(&id) = ids.get(&next) {
                id
            } else {
                // State IDs occupy the upper 24 bits of a transition. This tighter
                // limit also bounds memory use if a vocabulary change causes growth.
                assert!(states.len() < 500_000, "unexpected determinization growth");
                let id = u32::try_from(states.len()).expect("too many DFA states");
                states.push(next.clone());
                ids.insert(next, id);
                id
            };
            rows.push((id << 8) | u32::from(cost.to_le_bytes()[0]));
        }
        index += 1;
        if index % 10_000 == 0 {
            eprintln!("{index} / {} states", states.len());
        }
    }
    eprintln!(
        "done {index}/{} states, {} MB",
        states.len(),
        rows.len() * 4 / 1_048_576
    );
    assert_eq!(index, states.len());
    rows
}

fn minimize(rows: &[u32]) -> Vec<u32> {
    // Moore refinement. A state's final cost is zero; equivalence therefore requires
    // equal transition deltas and equivalent destination states for every byte.
    let mut classes = vec![0u32; rows.len() / 256];
    let mut previous_count = 1;
    let representatives = loop {
        let mut signatures = FxHashMap::default();
        let mut representatives = Vec::new();
        let mut next_classes = Vec::with_capacity(classes.len());
        for (state, row) in rows.as_chunks::<256>().0.iter().enumerate() {
            let signature: Vec<u32> = row
                .iter()
                .map(|&edge| (classes[(edge >> 8) as usize] << 8) | (edge & 255))
                .collect();
            let id = *signatures.entry(signature).or_insert_with(|| {
                let id = u32::try_from(representatives.len()).expect("too many DFA classes");
                representatives.push(state);
                id
            });
            next_classes.push(id);
        }
        classes = next_classes;
        if representatives.len() == previous_count {
            break representatives;
        }
        previous_count = representatives.len();
    };
    assert_eq!(classes[0], 0);
    representatives
        .into_iter()
        .flat_map(|state| {
            rows[state * 256..(state + 1) * 256]
                .iter()
                .map(|&edge| (classes[(edge >> 8) as usize] << 8) | (edge & 255))
        })
        .collect()
}

fn serialize(rows: &[u32]) -> Vec<u8> {
    let mut blocks = Vec::<u32>::new();
    let mut block_ids = FxHashMap::<Vec<u32>, u16>::default();
    let mut indices = Vec::new();
    for row in rows.as_chunks::<256>().0 {
        for block in row.as_chunks::<16>().0 {
            let block = block.to_vec();
            let id = *block_ids.entry(block.clone()).or_insert_with(|| {
                let id = u16::try_from(blocks.len() / 16).expect("too many blocks");
                blocks.extend(&block);
                id
            });
            indices.push(id);
        }
    }
    let mut binary = b"TOKDFA01".to_vec();
    binary.extend(
        u32::try_from(rows.len() / 256)
            .expect("too many DFA states")
            .to_le_bytes(),
    );
    binary.extend(
        u32::try_from(blocks.len() / 16)
            .expect("too many DFA blocks")
            .to_le_bytes(),
    );
    binary.extend(indices.iter().flat_map(|id| id.to_le_bytes()));
    binary.extend(blocks.iter().flat_map(|edge| edge.to_le_bytes()));
    eprintln!(
        "{} minimized states, {} blocks, {} bytes",
        rows.len() / 256,
        blocks.len() / 16,
        binary.len()
    );
    binary
}

fn validate_fast_paths(pieces: &BTreeSet<Vec<u8>>) {
    // The runtime counts digits and equal whitespace runs in closed form.
    // Reject new vocabulary pieces that would cross these independent seams
    // or change the supported run lengths.
    for piece in pieces {
        assert!(!piece.is_empty(), "empty vocabulary piece");
        if piece.iter().any(u8::is_ascii_digit) {
            assert!(piece.len() <= 3 && piece.iter().all(u8::is_ascii_digit));
        }
        if let Some(&byte) = piece.iter().find(|&&b| matches!(b, b' ' | b'\t' | b'\n')) {
            assert!(piece.iter().all(|&other| other == byte));
            assert!(piece.len() <= 16 || byte == b'\n' && matches!(piece.len(), 24 | 32));
        }
    }
    for exponent in 1..=3 {
        let width = usize::try_from(exponent).unwrap();
        for number in 0..10usize.pow(exponent) {
            assert!(pieces.contains(format!("{number:0width$}").as_bytes()));
        }
    }
    for byte in *b" \t\n" {
        for length in 1..=32 {
            if length <= 16 || byte == b'\n' && matches!(length, 24 | 32) {
                assert!(pieces.contains(&vec![byte; length]));
            }
        }
    }
}

/// Derive the scalar floor and multi-scalar bitmap directly from vocabulary pieces.
fn scalar_tables(pieces: &BTreeSet<Vec<u8>>) -> (Vec<u8>, Vec<u8>) {
    let mut floor = vec![0u8; 16_384];
    let mut multi_scalar = vec![0u8; 8192];
    let mut long_prefixes = BTreeSet::new();
    for piece in pieces {
        if let Ok(text) = std::str::from_utf8(piece) {
            if text.chars().count() > 1 {
                for ch in text.chars() {
                    let cp = ch as usize;
                    assert!(cp < 65536, "update the supplementary-scalar shortcut");
                    multi_scalar[cp / 8] |= 1 << (cp % 8);
                }
            } else {
                let ch = text.chars().next().unwrap();
                if !matches!(ch, '\u{1}'..='\u{4}') {
                    let cp = ch as usize;
                    assert!(cp < 65536);
                    floor[cp / 8] |= 1 << (cp % 8);
                }
            }
        } else {
            match piece.as_slice() {
                [a, b] => {
                    let prefix = u16::from_be_bytes([*a, *b]) as usize;
                    floor[8192 + prefix / 8] |= 1 << (prefix % 8);
                }
                [a, b, c] => {
                    long_prefixes.insert([*a, *b, *c]);
                }
                _ => panic!("unsupported UTF-8 fallback prefix"),
            }
        }
    }
    assert_eq!(
        long_prefixes,
        BTreeSet::from([
            [0xf0, 0x9f, 0x91],
            [0xf0, 0x9f, 0x92],
            [0xf0, 0x9f, 0x93],
            [0xf0, 0x9f, 0x98],
        ])
    );
    (floor, multi_scalar)
}

/// Independent dynamic programming reference: either consume one fallback byte,
/// or match a complete vocabulary piece starting at this byte offset.
fn reference_count(trie: &[Node], bytes: &[u8]) -> usize {
    let mut costs = vec![usize::MAX; bytes.len() + 1];
    costs[0] = 0;
    for start in 0..bytes.len() {
        let next_cost = costs[start] + 1;
        costs[start + 1] = costs[start + 1].min(next_cost);
        let mut node = 0;
        for (offset, byte) in bytes[start..].iter().enumerate() {
            let Some(&child) = trie[node].edges.get(byte) else {
                break;
            };
            node = child as usize;
            if trie[node].terminal {
                costs[start + offset + 1] = costs[start + offset + 1].min(next_cost);
            }
        }
    }
    costs[bytes.len()]
}

fn validate_dfa(trie: &[Node], rows: &[u32], pieces: &BTreeSet<Vec<u8>>) {
    let check = |bytes: &[u8]| {
        let mut state = 0;
        let mut count = 0isize;
        for &byte in bytes {
            let edge = rows[state * 256 + byte as usize];
            state = (edge >> 8) as usize;
            count += isize::from(i8::from_le_bytes([edge.to_le_bytes()[0]]));
        }
        assert_eq!(
            usize::try_from(count).expect("DFA token count cannot be negative"),
            reference_count(trie, bytes),
            "{bytes:?}"
        );
    };
    for piece in pieces {
        check(piece);
        let mut surrounded = b"\x01hello\x02 ".to_vec();
        surrounded.extend(piece);
        surrounded.extend(b"'s\x02\n");
        check(&surrounded);
    }
    // Includes invalid UTF-8: the DFA itself operates on arbitrary byte streams.
    let mut seed = 0x1234_5678_u32;
    for _ in 0..10_000 {
        let mut bytes = Vec::new();
        for _ in 0..64 {
            seed ^= seed << 13;
            seed ^= seed >> 17;
            seed ^= seed << 5;
            bytes.push(seed.to_le_bytes()[0]);
        }
        check(&bytes);
    }
}

fn short_words(trie: &[Node]) -> Vec<u8> {
    let mut table = vec![0; 128 + 128 * 128];
    for a in (0..128u8).filter(u8::is_ascii_alphabetic) {
        for b in std::iter::once(None).chain((0..128u8).filter(u8::is_ascii_alphabetic).map(Some)) {
            let shifted = a.is_ascii_uppercase() && b.is_none_or(|b| b.is_ascii_lowercase());
            let mut marked = Vec::new();
            if shifted {
                marked.push(3);
            }
            marked.push(1);
            marked.push(if shifted { a.to_ascii_lowercase() } else { a });
            if let Some(b) = b {
                marked.push(b);
            }
            marked.push(2);
            let index = b.map_or(a as usize, |b| 128 + a as usize * 128 + b as usize);
            table[index] = u8::try_from(reference_count(trie, &marked)).unwrap();
        }
    }
    table
}
